# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/lexus-design-collection/it" # the subpath of your site, e.g. /blog/
img:     "/lexus-design-collection/it/_assets/img"
css:     "/lexus-design-collection/it/_assets/css"
js:      "/lexus-design-collection/it/_assets/js"
video:   "/lexus-design-collection/it/_assets/video"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed



################################################################################
#   LOCALE
################################################################################

title: Lexus Design Collection
description: >
  Parti per un viaggio nel design con Lexus e Secret Escapes. Mettiti alla guida del nuovo Lexus&nbsp;UX Hybrid e preparati a vivere un'avventura urbana senza paragoni. Tra hotel di design griffati e location all'ultima moda, Roma e Milano non hanno più segreti per te. Scopri con noi l'esclusiva Design Collection.
copyright: '© Copyright <span class="js-year">2019</span> Secret Escapes'

# client
client:
  name: Lexus
  link: https://www.lexus.it/

# secret escapes
secret-escapes:
  current-sales: https://it.secretescapes.com/offerte-in-corso
  nav:
    - title: Offerte In Corso
      link: "{{site.secret-escapes.current-sales}}"
    - title: Come Funziona
      link: https://it.secretescapes.com/come-funziona
    - title: Buoni Regalo
      link: https://it.secretescapes.com/offerta-voucher
    - title: "{{site.title}}"
      link: "{{site.baseurl}}"

# offer card
offer-card:
  view-offer: Scopri L'offerta
  saved: Risparmia fino al&nbsp;
  from: A partire da
  price: "{{offer.price}}€"
  expires:
    # need to manually update the js, just here for reference. Project path: _assets/js/_components/offer-countdown.js
    today: Scade oggi
    number-of-days: Scade tra 99 giorni
    one-day: Scade tra 1 giorno

# test drive promo
test-drive:
  title: Prova il nuovo Lexus&nbsp;UX Hybrid con tecnologia Full Hybrid Electric
  description: Preparati a vivere un'avventura metropolitana sul primo crossover compatto ibrido elettrificato
  cta: Prenota ora il tuo test drive
  url: https://www.lexus.it/forms/secret-escapes/test-drive-se

offer-page:
  country: Italia
  world: Resto del mondo

feature-video:
  cta: Guarda il video
  url: https://www.youtube.com/watch?v=LRJuATsMlMM