# Site settings
title: Lexus Design Samling
client:
  name: Lexus
  link: https://www.lexus.no
core-se-link: https://no.secretescapes.com/aktuelle-tilbud
description: >
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/lexus-design-collection/no" # the subpath of your site, e.g. /blog/
img:     "/lexus-design-collection/no/_assets/img"
css:     "/lexus-design-collection/no/_assets/css"
js:      "/lexus-design-collection/no/_assets/js"

#global content
test-drive:
  cta: Book a Test Drive
  url: https://forms.lexus.co.uk/webforms/secretescapestestdrive.aspx


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed