# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/lexus-design-collection/se" # the subpath of your site, e.g. /blog/
img:     "/lexus-design-collection/se/_assets/img"
css:     "/lexus-design-collection/se/_assets/css"
js:      "/lexus-design-collection/se/_assets/js"
video:   "/lexus-design-collection/se/_assets/video"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed



################################################################################
#   LOCALE
################################################################################

title: Lexus Design Collection
description: >
  Upptäck en värld av design med Lexus och Secret Escapes. Åk iväg på ditt eget urbana äventyr med Lexus UX och låt städerna inspirera dig. Lexus Design Collection innehåller några av världens finaste designhotell och en del av våra mest banbrytande hotell, från Stockholm till Göteborg.
copyright: '© Copyright <span class="js-year">2019</span> Secret Escapes'

# client
client:
  name: Lexus
  link: https://www.lexus.se/

# secret escapes
secret-escapes:
  current-sales: https://www.secretescapes.se/aktuella-kampanjer
  nav:
    - title: Aktuella kampanjer
      link: "{{site.secret-escapes.current-sales}}"
    - title: Ekovänligt
      link: https://www.secretescapes.se/ekovanligt/filter
    - title: Toppdestinationer 2019
      link: https://www.secretescapes.se/toppdestinationer2019/filter
    - title: "{{site.title}}"
      link: "{{site.baseurl}}"

# offer card
offer-card:
  view-offer: Se erbjudande
  saved: Spara upp till&nbsp;
  from: Från
  price: "{{offer.price}} kr"
  expires:
    # need to manually update the js, just here for reference. Project path: _assets/js/_components/offer-countdown.js
    today: Slutar idag
    number-of-days: Slutar om 99 dagar
    one-day: Slutar om 1 dag

# test drive promo
test-drive:
  title: Provkör den nya självladdande hybridbilen Lexus UX
  description: Åk iväg på ett stadsäventyr med ett dygns provkörning av nya Lexus UX.
  cta: Boka en provkörning
  url: https://forms.lexus.co.uk/webforms/secretescapestestdrive.aspx

offer-page:
  country: Sverige
  world: Resten av världen

feature-video:
  cta: Se video
  url: https://www.youtube.com/watch?v=JRg0BYcitU0