# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/lexus-design-collection" # the subpath of your site, e.g. /blog/
img:     "/lexus-design-collection/_assets/img"
css:     "/lexus-design-collection/_assets/css"
js:      "/lexus-design-collection/_assets/js"
video:   "/lexus-design-collection/_assets/video"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed



################################################################################
#   LOCALE
################################################################################

title: Lexus Design Collection
description: >
  Discover a world of design with Lexus and Secret Escapes. Embark on your own urban adventure in the Lexus UX and let the city inspire you. From the world’s finest design hotels to the trendiest, urban design hangouts in London and Edinburgh, discover the Design Collection.
copyright: '© Copyright <span class="js-year">2019</span> Secret Escapes'

# client
client:
  name: Lexus
  link: https://www.lexus.co.uk/

# secret escapes
secret-escapes:
  current-sales: https://www.secretescapes.com/current-sales
  nav:
    - title: Current Sales
      link: "{{site.secret-escapes.current-sales}}"
    - title: Spa
      link: https://www.secretescapes.com/spa
    - title: Smart Stays
      link: https://www.secretescapes.com/smartstays/filter
    - title: "{{site.title}}"
      link: "{{site.baseurl}}"

# offer card
offer-card:
  view-offer: View Offer
  saved: Save up to&nbsp;
  from: From
  price: "£{{offer.price}}"
  expires:
    # need to manually update the js, just here for reference. Project path: _assets/js/_components/offer-countdown.js
    today: Ending Today
    number-of-days: Ending in 99 days
    one-day: Ending in 1 day

# test drive promo
test-drive:
  title: Test drive the new Lexus UX Self-Charging Hybrid
  description: Head for your own urban adventure with 24hr test-drives in the new Lexus UX.
  cta: Book a Test Drive
  url: https://forms.lexus.co.uk/webforms/secretescapestestdrive.aspx

offer-page:
  country: UK
  world: Rest of the world

feature-video:
  cta: Watch Video
  url: https://www.youtube.com/watch?v=JRg0BYcitU0