# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/lexus-design-collection/de" # the subpath of your site, e.g. /blog/
img:     "/lexus-design-collection/de/_assets/img"
css:     "/lexus-design-collection/de/_assets/css"
js:      "/lexus-design-collection/de/_assets/js"
video:   "/lexus-design-collection/de/_assets/video"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed



################################################################################
#   LOCALE
################################################################################

title: Lexus Design Kollektion
description: >
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt, laborum, accusamus. Provident iste alias iure eum, quidem, porro officiis earum quas sunt cumque modi dignissimos.
copyright: '© Copyright <span class="js-year">2019</span> Secret Escapes'

# client
client:
  name: Lexus
  link: https://www.lexus.de/

# secret escapes
secret-escapes:
  current-sales: https://www.secretescapes.de/aktuelle-angebote
  nav:
    - title: Current Sales
      link: "{{site.secret-escapes.current-sales}}"
    - title: Spa
      link: https://www.secretescapes.com/spa
    - title: Smart Stays
      link: https://www.secretescapes.com/smartstays/filter
    - title: "{{site.title}}"
      link: "{{site.baseurl}}"

# offer card
offer-card:
  view-offer: View Offer
  saved: Save up to&nbsp;
  from: From
  price: "£{{offer.price}}"
  expires:
    # need to manually update the js, just here for reference. Project path: _assets/js/_components/offer-countdown.js
    today: Ending Today
    number-of-days: Ending in 99 days
    one-day: Ending in 1 day

# test drive promo
test-drive:
  title: Test drive the Lexus UX
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio dicta eligendi accusantium quibusdam iste eos cum incidunt placeat magni accusamus nemo fugiat recusandae, provident a impedit quas assumenda deleniti! Molestiae.
  cta: Book a Test Drive
  url: https://forms.lexus.co.uk/webforms/secretescapestestdrive.aspx