# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/lexus-design-collection/es" # the subpath of your site, e.g. /blog/
img:     "/lexus-design-collection/es/_assets/img"
css:     "/lexus-design-collection/es/_assets/css"
js:      "/lexus-design-collection/es/_assets/js"
video:   "/lexus-design-collection/es/_assets/video"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed



################################################################################
#   LOCALE
################################################################################

title: Colección De Diseño Lexus
description: >
  Descubre un mundo de diseño con Lexus y Secret Escapes. Embárcate en tu propia aventura urbana en el Lexus UX y déjate inspirar por la ciudad. Desde los hoteles de diseño más increíbles del mundo hasta los escenarios más creativos de Barcelona y Bilbao, capaces de traspasar los límites de la modernidad: explora la Colección de Diseño.
copyright: '© Copyright <span class="js-year">2019</span> Secret Escapes'

# client
client:
  name: Lexus
  link: https://www.lexusauto.es/

# secret escapes
secret-escapes:
  current-sales: https://es.secretescapes.com/ventas-actuales
  nav:
    - title: Ventas Disponibles
      link: "{{site.secret-escapes.current-sales}}"
    - title: Vales Regalo
      link: https://es.secretescapes.com/oferta-cupon
    - title: "{{site.title}}"
      link: "{{site.baseurl}}"

# offer card
offer-card:
  view-offer: Ver Oferta
  saved: Ahorra hasta un&nbsp;
  from: Desde
  price: "{{offer.price}} €"
  expires:
    # need to manually update the js, just here for reference. Project path: _assets/js/_components/offer-countdown.js
    today: Termina hoy
    number-of-days: Termina en 99 días
    one-day: Termina en 1 día

# test drive promo
test-drive:
  title: Prueba el nuevo híbrido autorrecargable Lexus UX
  description: Lánzate a vivir tu propia escapada urbana con una prueba de conducción de 24 horas en el nuevo Lexus UX.
  cta: Reserva Una Prueba De Conducción
  url: https://forms.lexus.co.uk/webforms/secretescapestestdrive.aspx

offer-page:
  country: España
  world: Resto del mundo

feature-video:
  cta: Ver Vídeo
  url: https://www.youtube.com/watch?v=JRg0BYcitU0