# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/lexus-design-collection/de" # the subpath of your site, e.g. /blog/
img:     "/lexus-design-collection/de/_assets/img"
css:     "/lexus-design-collection/de/_assets/css"
js:      "/lexus-design-collection/de/_assets/js"
video:   "/lexus-design-collection/de/_assets/video"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed



################################################################################
#   LOCALE
################################################################################

title: Lexus Design Collection
description: >
  Entdecken Sie mit Lexus und Secret Escapes eine Welt des Designs. Ihr urbanes Abenteuer wartet, denn wir schicken Sie mit dem Lexus UX auf einen inspirierenden City-Trip. Von den besten Designhotels der Welt bis zu den ultimativen Hotspots Berlin und Hamburg: Erleben Sie die Design-Collection.
copyright: '© Copyright <span class="js-year">2019</span> Secret Escapes'

# client
client:
  name: Lexus
  link: https://www.lexus.de/

# secret escapes
secret-escapes:
  current-sales: https://www.secretescapes.de/aktuelle-angebote
  nav:
    - title: Aktuelle Angebote
      link: "{{site.secret-escapes.current-sales}}"
    - title: Unser Geheimnis
      link: https://www.secretescapes.de/unser-geheimnis
    - title: Reisekategorien
      link: https://www.secretescapes.de/reisekategorien/filter
    - title: "{{site.title}}"
      link: "{{site.baseurl}}"

# offer card
offer-card:
  view-offer: Alle Angebote
  saved: Sparen Sie bis zu&nbsp;
  from: Ab
  price: "{{offer.price}} €"
  expires:
    # need to manually update the js, just here for reference. Project path: _assets/js/_components/offer-countdown.js
    today: Endet heute
    number-of-days: "Verbleibende Zeit: 99 Tage"
    one-day: "Verbleibende Zeit: 1 Tag"

# test drive promo
test-drive:
  title: Jetzt den neuen selbstladenden Lexus UX Hybrid probefahren
  description: Erleben Sie Ihr eigenes City-Abenteuer bei einer 24-stündigen Probefahrt des neuen Lexus UX.
  cta: Probefahrt vereinbaren
  url: https://forms.lexus.co.uk/webforms/secretescapestestdrive.aspx

offer-page:
  country: Deutschland
  world: Weltweit

feature-video:
  cta: Zum Video
  url: https://www.youtube.com/watch?v=JRg0BYcitU0