# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/lexus-design-collection/no" # the subpath of your site, e.g. /blog/
img:     "/lexus-design-collection/no/_assets/img"
css:     "/lexus-design-collection/no/_assets/css"
js:      "/lexus-design-collection/no/_assets/js"
video:   "/lexus-design-collection/no/_assets/video"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed



################################################################################
#   LOCALE
################################################################################

title: Lexus Design Collection
description: >
  Oppdag en verden av design med Lexus og Secret Escapes. Legg ut på et urbant eventyr i en Lexus UX og la byen inspirere deg. Utforsk Design Collection med noen av verdens flotteste designhoteller og finn de kuleste stedene å henge med design i fokus i Bergen og Oslo.
copyright: '© Copyright <span class="js-year">2019</span> Secret Escapes'

# client
client:
  name: Lexus
  link: https://www.lexus.no

# secret escapes
secret-escapes:
  current-sales: https://no.secretescapes.com/aktuelle-tilbud
  nav:
    - title: Aktuelle tilbud
      link: "{{site.secret-escapes.current-sales}}"
    - title: Wow-faktor
      link: https://no.secretescapes.com/drmmehotell/filter
    - title: Storbydrømmer
      link: https://no.secretescapes.com/storby/filter
    - title: "{{site.title}}"
      link: "{{site.baseurl}}"

# offer card
offer-card:
  view-offer: Se tilbud
  saved: Spar innti&nbsp;
  from: Fra
  price: "kr {{offer.price}}"
  expires:
    # need to manually update the js, just here for reference. Project path: _assets/js/_components/offer-countdown.js
    today: Avslutter i dag
    number-of-days: Avslutter om 99 dager
    one-day: Avslutter om 1 dag

# test drive promo
test-drive:
  title: Prøvekjør nye Lexus&nbsp;UX
  description: Forhåndsbestill prøvekjøring for muligheten til å oppleve den nye selvladende hybriden Lexus&nbsp;UX.
  cta: Bestill prøvekjøring
  url: https://www.lexus.no/forms/secret-escapes/test-drive-se

offer-page:
  country: Norge
  world: Resten av verden

feature-video:
  cta: Se video
  url: https://www.youtube.com/watch?v=JRg0BYcitU0